name: CI Compile check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Install MySQL server
        run: |
         sudo apt-get update
         sudo apt-get install -y mysql-server
         sudo systemctl start mysql
         sudo systemctl status mysql
         sudo mysql --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS cloudcourse;"
         sudo mysql --user=root --password=root -e "SHOW DATABASES;"
         sudo mysql --user=root --password=root -e "USE cloudcourse;" 

      - name: Set up environment variables
        run: |
          echo "DB_DIALECT=mysql" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_USERNAME=root" >> $GITHUB_ENV
          echo "DB_PASSWORD=sweety" >> $GITHUB_ENV
          echo "DB_NAME=cloudcourse" >> $GITHUB_ENV

      - name: Run tests
        run: npm test

      